### PR TITLE
addressing issue #38 (be able to read PDFs)

### PR DESCRIPTION
**Pull request by jstaerk**
using https://mustangproject.org

### CODE REVIEW

**Comment by stbischof** [comment]
but a Zugpferd is not an XRechnung.

**Comment by jstaerk** [comment]
> but a Zugpferd is not an XRechnung.

That depends. Fundamentally ZF2 can be expressed as XML only, in which case a EN16931 profile ZF2 can be identical to a UN/CEFACT XRechnung under the condition that the ZF2 specifies the attributes required by XR, like Sellercontact and BuyerReference. It even runs through the kosit validator if you add the fragment mentioned in https://github.com/itplr-kosit/validator/issues/38. Interestingly even with the #xrechnung RAM:ID-fragment it would probably be a ZF2 file, so I would say a UN/CEFACT XR is always a also EN16931 ZF2 file but a ZF2 xml variant may only comply to a XR. However, usually a ZF2 file would be a PDF/A-3 file embedding the XML file.

My users apparently want to support both XR for B2C as well as ZF2 for B2B (e.g. Deutsche Bahn) and B2C (e.g. EON, I assume both Deutsche Bahn and EON are not using mustang, but that's a different story). My users usually they provide their own XML file but sometimes they also have it generated by Mustang. 

I recommend them to extract the XML from the PDF file, add the RAM:ID-fragment, and run it through the kosit validator to make sure the XR minimum criteria (Seller contact...) are met and e.g. their cash discount is formatted like XR suggests. 

However, it would be easier for them to check if they did not always have to extract the XML file from the PDF, that's why I suggested the patch. The result would be that they generate a valid ZF2 file, and if the PDF is not needed they just submit the XML file, which would then also be a valid XR (we should discuss about the RAM:ID-fragment).

**Comment by rkottmann** [comment]
Dear @jstaerk , thank you very much for this interesting PR. We will consider the PR very carefully. Just to give you a bit more background:

* The aim of the validator is to be an engine, which can validate any XML which is based and depends on a configuration
* It means the validator is very general and the specifics are in the configuration. Currently, we published two different configurations one for XRechnung and one for xgewerbeanzeige
* Your solution is implemented in the validator engine. However, according to our architecture, it would be better to place the solution a new configuration. However, you are technically right that the PDF extraction itself would have to be placed in the validator engine. This is a trade-off we have to consider carefully.

While writing this, I start to think of another solution:  We could consider to make the XML extraction an own standalone little module (let's name it zugferd2xrechnung for exmaple). This would render the above consideration obsolete and it would allow to chain bith the extractor and validator together like in a UNIX pipeline:

` zugferd2xrechnung | java -jar  validationtool-<version>-standalone.jar  -s <scenario-config-file> [OPTIONS]` 

It would just require to make sure that the validator properly accepts XML from STDIN.

**Comment by jstaerk** [comment]
Hi

> * Your solution is implemented in the validator engine. However, according to our architecture, it would be better to place the solution a new configuration. However, you are technically right that the PDF extraction itself would have to be placed in the validator engine. This is a trade-off we have to consider carefully.
> 
> While writing this, I start to think of another solution: We could consider to make the XML extraction an own standalone little module (let's name it zugferd2xrechnung for exmaple). This would render the above consideration obsolete and it would allow to chain bith the extractor and validator together like in a UNIX pipeline:
> 
> ` zugferd2xrechnung | java -jar validationtool-<version>-standalone.jar -s <scenario-config-file> [OPTIONS]`
> 
> It would just require to make sure that the validator properly accepts XML from STDIN.

Piping could be interesting because of it's versatility (I would rather call it `extractxmlfrompdf`) but it might consider some thoughs as regards potential multiple input files (potentially mixed with some PDFs that do not have embedded XML at all) or input from streams instead of files. 

Somehow a configuration sounds more sustainable: could that configuration be extended to something like a plugin concept which could also contain code? E.g. https://github.com/ZUGFeRD/ZUV/ uses VeraPDF to also validate the PDF file but that would add some megabytes not everybody needs to validate a simple XRechnung. But with plugins a joint XGewerbeanzeige/XRechnung/ZUGFeRD/Factur-X-Validator could be possible :-)

If it's about the size (I did not check the filesize of your validator after adding mustang) maybe one could also consider some kind of a specialized lightweight extractor library.

kind regards
Jochen

**Comment by rkottmann** [comment]
After some considearations, we decided not to integrate this functionality in the core of the validator. 

However, next to the standard piping variant, we consider a plugin system, so that interested parties can easily provide such a finctionality. In preparation for this we already made the configuration of the validator accessibale via API (see configuration_api branch) to be released in the next two weeks. 

The validator can also be run in deamon mode with a simple REST API for validation. That will be another option to combine XML extraction from PDF with validation.

Hope you understand the reasoning. 

Thanks again for your contribution. Although we will not include your code, you triggered some intersting ideas and developments!

I will close this request for now.

**Comment by apenski** [comment]
with the upcoming version you can implement something like this:

```java
@RequiredArgsConstructor
public class MyZugferdInput implements Input {

private final ZugferdEntity;

@Override
public Source getSource(){
 // return a StreamSource or DOMSource or other Source here
}
...
}
```
And then use it like this 

```java
public static void main(String args[]){
  Configuration config = Configuration.load(...);
  DefaultCheck check = new DefaultCheck(config);

  Input pdfInput= new MyZugferdInput( /*put your pdf entity here */);
  Result result = check.checkInput(pdfInput);
  //examine your result here
}

```

**Comment by jstaerk** [comment]
> Hope you understand the reasoning.
> 
sure, no problem, I just wanted to show that it's not impossible. Maybe not even very complicated.

**Pull request closed without merging**
