### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by christian-schlichtherle**

### CODE REVIEW

**Comment by christian-schlichtherle** [comment]
See https://central.sonatype.org/pages/producers.html .

**Comment by christian-schlichtherle** [comment]
Does anyone care to comment on this PR?

**Comment by apenski** [comment]
Well, actually I've ignored it so far, since it looked related to publishing to maven central and we have some organisational issues with this. KoSIT does not want to publish with a github-related groupId nor did they have decided which groupId to use for this. The claiming process wouldn't be easy since the KoSIT does not have access to meaningful domain. I hoped, we can find a solution till end of 2020, but this was not the case. 

I didn't notice that you've changed the PR and removed almost every stuff related to publishing. Sorry for that.

**Comment by christian-schlichtherle** [comment]
Thanks for merging.

**Comment by apenski** [comment]
Thanks for contributing!

**Pull request merged**
